# Data preparation

### Clean, transform and prepare a reproducible model table. Saved in `data/processed`

## 1. Libraries & settings

In [1]:
import sys
import pandas as pd
from pathlib import Path

## 2. Paths & load data

In [2]:
PROJECT_DIR = Path.cwd().resolve().parents[0]
sys.path.append(str(PROJECT_DIR))

from src.preprocessing import (
    PrepConfig, clean_columns_basic, apply_column_renames, build_model_table, save_processed
)

DATA_RAW  = PROJECT_DIR / "data" / "raw"
DATA_PROCESSED = PROJECT_DIR / "data" / "processed"
DATA_FILE = next(DATA_RAW.glob("*.csv"))
df_raw = pd.read_csv(DATA_FILE)
df_raw.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

## 3. Column config

In [3]:
cfg = PrepConfig(
    feature_cols=["Age", "Annual_income_thousands", "Spending_score"],
    category_cols=["Gender"],
    rename_map={
        "Spending Score (1-100)": "Spending_score",
        "Annual Income (k$)": "Annual_income_thousands"
    }
)

## 4. Data cleaning, renaming

In [4]:
df = apply_column_renames(df_raw, cfg.rename_map)
df = clean_columns_basic(df)
df

     CustomerID  Gender  Age  Annual_income_thousands  Spending_score
0             1    Male   19                       15              39
1             2    Male   21                       15              81
2             3  Female   20                       16               6
3             4  Female   23                       16              77
4             5  Female   31                       17              40
..          ...     ...  ...                      ...             ...
195         196  Female   35                      120              79
196         197  Female   45                      126              28
197         198    Male   32                      126              74
198         199    Male   32                      137              18
199         200    Male   30                      137              83

[200 rows x 5 columns]

## 5. Feature columns

In [5]:
model_df = build_model_table(df, cfg)
model_df

     Age  Annual_income_thousands  Spending_score  Gender
0     19                       15              39    Male
1     21                       15              81    Male
2     20                       16               6  Female
3     23                       16              77  Female
4     31                       17              40  Female
..   ...                      ...             ...     ...
195   35                      120              79  Female
196   45                      126              28  Female
197   32                      126              74    Male
198   32                      137              18    Male
199   30                      137              83    Male

[200 rows x 4 columns]

## 7. Save processed dataset

In [ ]:
out_csv = DATA_PROCESSED / "model_table.csv"
save_processed(model_df, out_csv)

## 8. Read-back check

In [7]:
check = pd.read_csv(out_csv)
check.head(), check.shape

(   Age  Annual_income_thousands  Spending_score  Gender
 0   19                       15              39    Male
 1   21                       15              81    Male
 2   20                       16               6  Female
 3   23                       16              77  Female
 4   31                       17              40  Female,
 (200, 4))